version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    working_directory: ~/code

jobs:
  buildDebug:
    executor: android
    steps:
      - checkout
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: |
            sudo chmod +x ./gradlew
      - restore_cache:
          keys:
            - gradle-{{ checksum "app/build.gradle" }}
      - run:
          name: Build Apks
          command: |
            ./gradlew clean assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "app/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

workflows:
  version: 2
  main:
    jobs:
      - buildDebug